junit:
  stage: test
  script:
    - mvn -B clean test
generate_artifacts:
<<<<<<< HEAD
  stage: deploy
  script:
    - mvn -B clean site package
  artifacts:
    paths:
    - target/s202*.jar 	
=======
stage: deploy
script:
- mvn -B clean site package
artifacts:
paths:
- target/s202*.jar
>>>>>>> 4814e5d51f833a246988dbabc04180548c4bb974
